### ISSUE TITLE
Python Script does not execute on docker

### ISSUE THREAD

**Issue by cgc007** [OmenWild/home-assistant-z-wave-graph#17]
I've masked my URL, but otherwise, the below is what I get when executing `z-wave-graph.py`:
```
Traceback (most recent call last):
  File "z-wave-graph.py", line 337, in <module>
    zwave = ZWave(config, args)
  File "z-wave-graph.py", line 195, in __init__
    m = self.request('/')
  File "z-wave-graph.py", line 213, in request
    response = get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '*<MyURL>*:8123/api/'
```

I'm running HA in docker, and I've followed the notes that were left on the readme.

I'm executing the command with `/usr/local/bin/python3 /config/bin/z-wave-graph.py`, which is where `z-wave-graph.py` is located in my share. It gives this error when running from the shell. The output from `home-assistant.log` is:

```
2019-07-17 13:05:05 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `/usr/local/bin/python3 /config/bin/z-wave-graph.py`, return code: 1
NoneType: None
```

**Comment by OmenWild** [comment]
I just pushed a new version that I've been sitting on for a while. It requires a long lived token to comply with security updates on the HA side. You will need to update shell_commands/z-wave-graph.yaml to add the token you generate. Give it a try and let me know if it helps. I _think_ most of the  `NoneType: None` errors are caused because the Python script cannot access the API.
